WebApplication3/WebApplication3/Models/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Models
{
    public class Player
    {   
        public int Id { get; set; }

        
        [Required]
        [Display(Name = "Број на дрес")]
        public int JerseyNumber { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Име")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Презиме")]
        public string LastName { get; set; }
        [Display(Name = "Тежина - kg ")]
        [Range(50, 150)]
        public int Weight { get; set; }
        [Display(Name = "Висина - cm")]
        [Range(150, 220)]
        public int Height { get; set; }
        
        [StringLength(50)]
        [Display(Name = "Позиција")]
        public string Position { get; set; }
        
        [StringLength(20)]
        [Display(Name = "Преферирана нога")]
        public string PrefferedLeg { get; set; }
        [Display(Name = "Постигнати голови во кариера")]
        [Range(0, 1500)]
        public int Goals { get; set; }
        [StringLength(20)]
        [Display(Name = "Држава")]
        public string Country { get; set; }



        [DataType(DataType.Date)]
        [Display(Name = "Роденден")]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Име и презиме")]
        public string FullName
        {
            get
            {
                return String.Format("{0} {1}", FirstName, LastName);
            }
        }
        [NotMapped]
        [Display(Name = "Возраст")]
        public int Age
        {
            get
            {
                TimeSpan span = DateTime.Now - BirthDate;
                double years = (double)span.TotalDays / 365.2425;
                return (int)years;
            }
        }
        public int? ContractId { get; set; }
        [ForeignKey("ContractId")]
        public Contract Contract { get; set; }
        public int? ImageId { get; set; }
        [ForeignKey("ImageId")]
        public Image Image { get; set; }



    }
}

WebApplication3/WebApplication3/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class ImagesController : Controller
    {
        private readonly WebApplication3Context _context;

        private readonly IWebHostEnvironment _hostEnvironment;

        public ImagesController(WebApplication3Context context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Images
        public async Task<IActionResult> Index()
        {
            var webApplication3Context = _context.Images.Include(i => i.Player);
            return View(await webApplication3Context.ToListAsync());
        }

        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Images
                .Include(i => i.Player)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // GET: Images/Create
        public IActionResult Create(int? playerId)
        {
            if (playerId != null)
            {
                IQueryable<Player> players = _context.Player.AsQueryable();
                players = players.Where(p => p.Id == playerId);
                ViewData["PlayerId"] = new SelectList(players, "Id", "FullName");
            }
            ViewData["PlayerId"] = new SelectList(_context.Player, "Id", "FullName");
            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ImageFile,PlayerId")] Image image)
        {
            if (ModelState.IsValid)
            {
                //Save image to wwwroot/image
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(image.ImageFile.FileName);
                string extension = Path.GetExtension(image.ImageFile.FileName);
                image.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await image.ImageFile.CopyToAsync(fileStream);
                }
                //Insert record
                _context.Add(image);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["PlayerId"] = new SelectList(_context.Player, "Id", "FullName", image.PlayerId);
            return View(image);
            
            
        }

        // GET: Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Images.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            ViewData["PlayerId"] = new SelectList(_context.Player, "Id", "FullName", image.PlayerId);
            return View(image);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ImageName,PlayerId")] Image image)
        {
            if (id != image.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(image);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlayerId"] = new SelectList(_context.Player, "Id", "FirstName", image.PlayerId);
            return View(image);
        }

        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Images
                .Include(i => i.Player)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.Images.FindAsync(id);

            //delete image from wwwroot/image
            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "image", image.ImageName);
            if (System.IO.File.Exists(imagePath))
                System.IO.File.Delete(imagePath);
            //delete the record
            _context.Images.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImageExists(int id)
        {
            return _context.Images.Any(e => e.Id == id);
        }
    }
}

WebApplication3/WebApplication3/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Data;
using WebApplication3.Models;
using WebApplication3.ViewModels;

namespace WebApplication3.Controllers
{
    public class PlayersController : Controller
    {
        private readonly WebApplication3Context _context;

        public PlayersController(WebApplication3Context context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index(string playerPosition, string playerCountry)
        {
            var webApplication3Context = _context.Player.Include(p => p.Contract).ThenInclude(p=>p.Team);
            IQueryable<Player> players = _context.Player.AsQueryable();
            IQueryable<string> positionQuery = _context.Player.OrderBy(m => m.Position).Select(m => m.Position).Distinct();
            IQueryable<string> countryQuery = _context.Player.OrderBy(m => m.Country).Select(m => m.Country).Distinct();
            if (!string.IsNullOrEmpty(playerPosition))
            {
                players = players.Where(x => x.Position == playerPosition);
            }
            if (!string.IsNullOrEmpty(playerCountry))
            {
                players = players.Where(x => x.Country == playerCountry);
            }
           

            var playerSearchViewModel = new PlayersSearchViewModel
            {
                Positions = new SelectList(await positionQuery.ToListAsync()),
                Countries = new SelectList(await countryQuery.ToListAsync()),
                Players = await players.ToListAsync()
            };
            return View(playerSearchViewModel);

        }
        // GET: Contracts
        public async Task<IActionResult> Index2()
        {
            var webApplication3Context = _context.Player.Include(c => c.Contract);
            return View(await webApplication3Context.ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player
                .Include(p => p.Contract).Include(p=>p.Image)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            ViewData["ContractId"] = new SelectList(_context.Contract, "Id", "Id");
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JerseyNumber,FirstName,LastName,Weight,Height,Position,PrefferedLeg,Goals,Country,BirthDate,ContractId")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ContractId"] = new SelectList(_context.Contract, "Id", "Id", player.ContractId);
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            ViewData["ContractId"] = new SelectList(_context.Contract, "Id", "Id", player.ContractId);
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JerseyNumber,FirstName,LastName,Weight,Height,Position,PrefferedLeg,Goals,Country,BirthDate,ContractId")] Player player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ContractId"] = new SelectList(_context.Contract, "Id", "Id", player.ContractId);
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player
                .Include(p => p.Contract)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Player.FindAsync(id);
            _context.Player.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Player.Any(e => e.Id == id);
        }
    }
}

WebApplication3/WebApplication3/Views/Players/Create.cshtml
@model WebApplication3.Models.Player

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JerseyNumber" class="control-label"></label>
                <input asp-for="JerseyNumber" class="form-control" />
                <span asp-validation-for="JerseyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrefferedLeg" class="control-label"></label>
                <input asp-for="PrefferedLeg" class="form-control" />
                <span asp-validation-for="PrefferedLeg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Goals" class="control-label"></label>
                <input asp-for="Goals" class="form-control" />
                <span asp-validation-for="Goals" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContractId" class="control-label"></label>
                <select asp-for="ContractId" class ="form-control" asp-items="ViewBag.ContractId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication3/WebApplication3/Views/Players/Delete.cshtml
@model WebApplication3.Models.Player

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JerseyNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JerseyNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrefferedLeg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrefferedLeg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Goals)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Goals)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contract)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contract.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication3/WebApplication3/Views/Players/Details.cshtml
@model WebApplication3.Models.Player

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="row">

        @if (Model.Image != null)
        {
            <dt class="col-sm-2">
                Слика
            </dt>
            <dd class="col-sm-10">

                <img class="lazyload" src="@("~/image/" + Model.Image.ImageName)" alt="No Image Available" asp-append-version="true" width="120" height="120" />
            </dd>
        }

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JerseyNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JerseyNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrefferedLeg)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrefferedLeg)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Goals)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Goals)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<div>
    @if (Model.Image == null) {
    <a asp-controller="Images" asp-action="Create" asp-route-playerId="@Model.Id">Upload Picture</a>
    }
    @if (Model.Image != null)
    {
        <a asp-controller="Images" asp-action="Delete" asp-route-id="@Model.Image.Id">Delete Picture</a>
    }
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication3/WebApplication3/Views/Players/Edit.cshtml
@model WebApplication3.Models.Player

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JerseyNumber" class="control-label"></label>
                <input asp-for="JerseyNumber" class="form-control" />
                <span asp-validation-for="JerseyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrefferedLeg" class="control-label"></label>
                <input asp-for="PrefferedLeg" class="form-control" />
                <span asp-validation-for="PrefferedLeg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Goals" class="control-label"></label>
                <input asp-for="Goals" class="form-control" />
                <span asp-validation-for="Goals" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContractId" class="control-label"></label>
                <select asp-for="ContractId" class="form-control" asp-items="ViewBag.ContractId"></select>
                <span asp-validation-for="ContractId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication3/WebApplication3/Views/Players/Index.cshtml
@model WebApplication3.ViewModels.PlayersSearchViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Players</h1>
<form asp-controller="Players" asp-action="Index" method="get">
    <p>
        <select asp-for="PlayerPosition" asp-items="Model.Positions">
            <option value="">Поцизиција</option>
        </select>
        <select asp-for="PlayerCountry" asp-items="Model.Countries">
            <option value="">Држава</option>
        </select>
        
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].JerseyNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].PrefferedLeg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].Goals)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Players[0].BirthDate)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Players) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JerseyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrefferedLeg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Goals)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @if (item.ContractId != null)
                {   
                    <a asp-controller="Contracts" asp-action="Details" asp-route-Id="@item.ContractId"> Договор на играчот </a>
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>